In [1]:
# Set retina display
%config InlineBackend.figure_format = 'retina'

In [ ]:
import numpy as np

t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([109.4, 187.5, 267.5, 331.9, 386.1, 428.4, 452.2, 498.1, 512.3, 513.0])

G = np.vstack([np.ones_like(t), t, -0.5*t**2]).T

m_L2 = np.linalg.inv(G.T @ G) @ G.T @ y
print (m_L2)

sigma = 8#np.std(G @ m_L2 - y)
print (sigma)

cov_m_L2 = np.linalg.inv(G.T @ G) * sigma**2
print (cov_m_L2)

v = np.sum((G @ m_L2 - y)**2) / sigma**2
print (v)

# chisquare distribution
from scipy.stats import chi2
p_value = 1 - chi2.cdf(v, df=len(y)-len(m_L2))

[16.40833333 96.97128788  9.40833333]
8
[[ 88.53333333 -33.6         -5.33333333]
 [-33.6         15.44242424   2.66666667]
 [ -5.33333333   2.66666667   0.48484848]]
4.180959043560617
